apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: votingapp
spec:
  generators:
  - list:
      elements:
      - cluster: k8s-voting-app-main
        url: 'https://kubernetes.default.svc'
  template:
    metadata:
      name: '{{cluster}}-votingapp'
    spec:
      project: default
      source:
        repoURL: https://github.com/jun3442/votingApp.git
        targetRevision: HEAD
        path: k8s-voting-app-main/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: default
